name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - clean-main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan \
            -var="github_token=${{ secrets.GH_TOKEN }}" \
            -var="ecr_repo_name=my-node-ecr" \
            -var="app_repo_url=https://github.com/LemonLucy/terraform-selfservice.git" \
            -var="ami_id=ami-0c9c942bd7bf113a2" \
            -var="instance_type=t3.micro" \
            -var="instance_name=my-selfservice-ec2" \
            -var="aws_region=us-east-1" \
            -var="eks_cluster_name=my-cluster-dev" \
            -var="node_instance_type=t3.medium" \
            -var="desired_capacity=2" \
            -var='subnet_ids=["subnet-0484b14156d3ca84a","subnet-07ef5ba64c65d0a4b"]' \
            -var="github_owner=LemonLucy" \
            -var="github_repo=terraform-selfservice"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve \
            -var="github_token=${{ secrets.GH_TOKEN }}" \
            -var="ecr_repo_name=my-node-ecr" \
            -var="app_repo_url=https://github.com/LemonLucy/terraform-selfservice.git" \
            -var="ami_id=ami-0c9c942bd7bf113a2" \
            -var="instance_type=t3.micro" \
            -var="instance_name=my-selfservice-ec2" \
            -var="aws_region=us-east-1" \
            -var="eks_cluster_name=my-cluster-dev" \
            -var="node_instance_type=t3.medium" \
            -var="desired_capacity=2" \
            -var='subnet_ids=["subnet-0484b14156d3ca84a","subnet-07ef5ba64c65d0a4b"]' \
            -var="github_owner=LemonLucy" \
            -var="github_repo=terraform-selfservice"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}